INSERT INTO pirates(id, name) VALUES (1, 'James Allison');
INSERT INTO pirates(id, name) VALUES (2, 'Thomas Anstis');
INSERT INTO pirates(id, name) VALUES (3, 'Leigh Ashworth');
INSERT INTO pirates(id, name) VALUES (4, 'John Auger');
INSERT INTO pirates(id, name) VALUES (5, 'Adam Baldridge');
INSERT INTO pirates(id, name) VALUES (6, 'Jonathan Barnet');
INSERT INTO pirates(id, name) VALUES (7, 'Thomas Barrow');
INSERT INTO pirates(id, name) VALUES (8, 'Don Benito');
INSERT INTO pirates(id, name) VALUES (9, 'Charles Bellamy');
INSERT INTO pirates(id, name) VALUES (10, 'Samuel Bellamy (Black Sam)');
INSERT INTO pirates(id, name) VALUES (11, 'Blackbeard (Edward Teach)');
INSERT INTO pirates(id, name) VALUES (12, 'Black Caesar');
INSERT INTO pirates(id, name) VALUES (13, 'Augustin Blanco');
INSERT INTO pirates(id, name) VALUES (14, 'Richard Bobbington');
INSERT INTO pirates(id, name) VALUES (15, 'Jean Bonadvis');
INSERT INTO pirates(id, name) VALUES (16, 'Stede Bonnet');
INSERT INTO pirates(id, name) VALUES (17, 'Anne Bonny');
INSERT INTO pirates(id, name) VALUES (18, 'George Booth');
INSERT INTO pirates(id, name) VALUES (19, 'John Bowen');
INSERT INTO pirates(id, name) VALUES (20, 'Joseph Bradish');
INSERT INTO pirates(id, name) VALUES (21, 'John Breholt');
INSERT INTO pirates(id, name) VALUES (22, 'Nicholas Brown');
INSERT INTO pirates(id, name) VALUES (23, 'Phineas Bunce');
INSERT INTO pirates(id, name) VALUES (24, 'Nathaniel Burches');
INSERT INTO pirates(id, name) VALUES (25, 'Josiah (Thomas) Burgess');
INSERT INTO pirates(id, name) VALUES (26, 'Samuel Burgess');
INSERT INTO pirates(id, name) VALUES (27, 'William Burke');
INSERT INTO pirates(id, name) VALUES (28, 'James Carnegie');
INSERT INTO pirates(id, name) VALUES (29, 'Canoot');
INSERT INTO pirates(id, name) VALUES (30, 'Dirk Chivers');
INSERT INTO pirates(id, name) VALUES (31, 'Adrian Claver');
INSERT INTO pirates(id, name) VALUES (32, 'Edward Coates');
INSERT INTO pirates(id, name) VALUES (33, 'Thomas Cocklyn');
INSERT INTO pirates(id, name) VALUES (34, 'John Cockram');
INSERT INTO pirates(id, name) VALUES (35, 'John Cole');
INSERT INTO pirates(id, name) VALUES (36, 'Robert Colley');
INSERT INTO pirates(id, name) VALUES (37, 'Thomas Collins');
INSERT INTO pirates(id, name) VALUES (38, 'Christopher Condent');
INSERT INTO pirates(id, name) VALUES (39, 'Joseph Cooper');
INSERT INTO pirates(id, name) VALUES (40, 'William Coward');
INSERT INTO pirates(id, name) VALUES (41, 'Captain Crapo');
INSERT INTO pirates(id, name) VALUES (42, 'Mary Critchett');
INSERT INTO pirates(id, name) VALUES (43, 'Robert Culliford');
INSERT INTO pirates(id, name) VALUES (44, 'Alexander Dalzeel');
INSERT INTO pirates(id, name) VALUES (45, 'Howell Davis');
INSERT INTO pirates(id, name) VALUES (46, 'Captain Davy');
INSERT INTO pirates(id, name) VALUES (47, 'Thomas Day');
INSERT INTO pirates(id, name) VALUES (48, 'Robert Deal');
INSERT INTO pirates(id, name) VALUES (49, 'Nicholas de Concepcion');
INSERT INTO pirates(id, name) VALUES (50, 'Mathurin Desmarestz');
-- INSERT INTO pirates(id, name) VALUES (51, 'Etienne de Montauban');
-- INSERT INTO pirates(id, name) VALUES (52, 'Francis Demont');
-- INSERT INTO pirates(id, name) VALUES (53, 'John Derdrake');
-- INSERT INTO pirates(id, name) VALUES (54, 'George Dew');
-- INSERT INTO pirates(id, name) VALUES (55, 'Edward England');
-- INSERT INTO pirates(id, name) VALUES (56, 'John Evans');
-- INSERT INTO pirates(id, name) VALUES (57, 'Henry Every (Avery)');
-- INSERT INTO pirates(id, name) VALUES (58, 'Joseph Faro');
-- INSERT INTO pirates(id, name) VALUES (59, 'John Fenn');
-- INSERT INTO pirates(id, name) VALUES (60, 'Lewis Ferdinando');
-- INSERT INTO pirates(id, name) VALUES (61, 'Francis Fernando');
-- INSERT INTO pirates(id, name) VALUES (62, 'James Fife');
-- INSERT INTO pirates(id, name) VALUES (63, 'William Fly');
-- INSERT INTO pirates(id, name) VALUES (64, 'William Fox');
-- INSERT INTO pirates(id, name) VALUES (65, 'Richard Frowd');
-- INSERT INTO pirates(id, name) VALUES (66, 'Ingela Gathenhielm');
-- INSERT INTO pirates(id, name) VALUES (67, 'Lars Gathenhielm');
-- INSERT INTO pirates(id, name) VALUES (68, 'Captain Gincks');
-- INSERT INTO pirates(id, name) VALUES (69, 'Richard Glover');
-- INSERT INTO pirates(id, name) VALUES (70, 'Robert Glover');
-- INSERT INTO pirates(id, name) VALUES (71, 'Christopher Goffe');
-- INSERT INTO pirates(id, name) VALUES (72, 'John Golden');
-- INSERT INTO pirates(id, name) VALUES (73, 'Thomas Goldsmith');
-- INSERT INTO pirates(id, name) VALUES (74, 'Thomas Griffin');
-- INSERT INTO pirates(id, name) VALUES (75, 'Captain Grinnaway');
-- INSERT INTO pirates(id, name) VALUES (76, 'Nathaniel Grubing');
-- INSERT INTO pirates(id, name) VALUES (77, 'Jean Baptiste Guedry');
-- INSERT INTO pirates(id, name) VALUES (78, 'Charles Harris');
-- INSERT INTO pirates(id, name) VALUES (79, 'John Halsey');
-- INSERT INTO pirates(id, name) VALUES (80, 'Israel Hands');
-- INSERT INTO pirates(id, name) VALUES (81, 'Don Miguel Enríquez (Henríquez)');
-- INSERT INTO pirates(id, name) VALUES (82, 'David Herriot');
-- INSERT INTO pirates(id, name) VALUES (83, 'John Hoar');
-- INSERT INTO pirates(id, name) VALUES (84, 'Benjamin Hornigold');
-- INSERT INTO pirates(id, name) VALUES (85, 'Thomas Howard');
-- INSERT INTO pirates(id, name) VALUES (86, 'Samuel Inless');
-- INSERT INTO pirates(id, name) VALUES (87, 'John Ireland');
-- INSERT INTO pirates(id, name) VALUES (88, 'John James');
-- INSERT INTO pirates(id, name) VALUES (89, 'Henry Jennings');
-- INSERT INTO pirates(id, name) VALUES (90, 'Henry Johnson');
-- INSERT INTO pirates(id, name) VALUES (91, 'Evan Jones');
-- INSERT INTO pirates(id, name) VALUES (92, 'John Julian');
-- INSERT INTO pirates(id, name) VALUES (93, 'James Kelly (James Gilliam)');
-- INSERT INTO pirates(id, name) VALUES (94, 'William (Captain) Kidd');
-- INSERT INTO pirates(id, name) VALUES (95, 'Henry King');
-- INSERT INTO pirates(id, name) VALUES (96, 'John King');
-- INSERT INTO pirates(id, name) VALUES (97, 'Montigny la Palisse');
-- INSERT INTO pirates(id, name) VALUES (98, 'Robert Lane');
-- INSERT INTO pirates(id, name) VALUES (99, 'Thomas Larimore');
-- INSERT INTO pirates(id, name) VALUES (100, 'Peter Lawrence');
-- INSERT INTO pirates(id, name) VALUES (101, 'John Leadstone (Old Captain Crackers)');
-- INSERT INTO pirates(id, name) VALUES (102, 'Francois Le Sage');
-- INSERT INTO pirates(id, name) VALUES (103, 'Francis Leslie');
-- INSERT INTO pirates(id, name) VALUES (104, 'Olivier Levasseur (Oliver La Buse)');
-- INSERT INTO pirates(id, name) VALUES (105, 'Samuel Liddell');
-- INSERT INTO pirates(id, name) VALUES (106, 'Edward (Ned) Low');
-- INSERT INTO pirates(id, name) VALUES (107, 'George Lowther');
-- INSERT INTO pirates(id, name) VALUES (108, 'Matthew Luke');
-- INSERT INTO pirates(id, name) VALUES (109, 'Philip Lyne');
-- INSERT INTO pirates(id, name) VALUES (110, 'John Martel');
-- INSERT INTO pirates(id, name) VALUES (111, 'Simon Mascarino');
-- INSERT INTO pirates(id, name) VALUES (112, 'William May');
-- INSERT INTO pirates(id, name) VALUES (113, 'Edward Miller');
-- INSERT INTO pirates(id, name) VALUES (114, 'Christopher Moody');
-- INSERT INTO pirates(id, name) VALUES (115, 'William Moody');
-- INSERT INTO pirates(id, name) VALUES (116, 'Captain Napin');
-- INSERT INTO pirates(id, name) VALUES (117, 'Thomas Nichols');
-- INSERT INTO pirates(id, name) VALUES (118, 'Richard Noland');
-- INSERT INTO pirates(id, name) VALUES (119, 'John Norcross');
-- INSERT INTO pirates(id, name) VALUES (120, 'Nathaniel North');
-- INSERT INTO pirates(id, name) VALUES (121, 'Amaro Pargo');
-- INSERT INTO pirates(id, name) VALUES (122, 'Major Penner');
-- INSERT INTO pirates(id, name) VALUES (123, 'Thomas Penniston');
-- INSERT INTO pirates(id, name) VALUES (124, 'James Plantain');
-- INSERT INTO pirates(id, name) VALUES (125, 'Daniel Porter');
-- INSERT INTO pirates(id, name) VALUES (126, 'John Prie');
-- INSERT INTO pirates(id, name) VALUES (127, 'John Pro');
-- INSERT INTO pirates(id, name) VALUES (128, 'John Quelch');
-- INSERT INTO pirates(id, name) VALUES (129, 'Calico Jack (John Rackham)');
-- INSERT INTO pirates(id, name) VALUES (130, 'George Raynor');
-- INSERT INTO pirates(id, name) VALUES (131, 'Mary Read');
-- INSERT INTO pirates(id, name) VALUES (132, 'William Read');
-- INSERT INTO pirates(id, name) VALUES (133, 'Lieutenant Richards');
-- INSERT INTO pirates(id, name) VALUES (134, 'John Rivers');
-- INSERT INTO pirates(id, name) VALUES (135, 'Bartholomew Roberts (Black Bart)');
-- INSERT INTO pirates(id, name) VALUES (136, 'Philip Roche');
-- INSERT INTO pirates(id, name) VALUES (137, 'Tempest Rogers');
-- INSERT INTO pirates(id, name) VALUES (138, 'Woodes Rogers');
-- INSERT INTO pirates(id, name) VALUES (139, 'John Russell');
-- INSERT INTO pirates(id, name) VALUES (140, 'Jasper Seagar');
-- INSERT INTO pirates(id, name) VALUES (141, 'Robert Semple');
-- INSERT INTO pirates(id, name) VALUES (142, 'Richard Shipton');
-- INSERT INTO pirates(id, name) VALUES (143, 'James Skyrme');
-- INSERT INTO pirates(id, name) VALUES (144, 'Francis Spriggs');
-- INSERT INTO pirates(id, name) VALUES (145, 'Daniel Stillwell');
-- INSERT INTO pirates(id, name) VALUES (146, 'Ralph Stout');
-- INSERT INTO pirates(id, name) VALUES (147, 'Thomas Sutton');
-- INSERT INTO pirates(id, name) VALUES (148, 'John Swann');
-- INSERT INTO pirates(id, name) VALUES (149, 'John Taylor');
-- INSERT INTO pirates(id, name) VALUES (150, 'Thomas Tew');
-- INSERT INTO pirates(id, name) VALUES (151, 'Captain Thompson');
-- INSERT INTO pirates(id, name) VALUES (152, 'John Thurber');
-- INSERT INTO pirates(id, name) VALUES (153, 'Regnier Tongrelow');
-- INSERT INTO pirates(id, name) VALUES (154, 'Richard Tookerman');
-- INSERT INTO pirates(id, name) VALUES (155, 'Turn Joe');
-- INSERT INTO pirates(id, name) VALUES (156, 'Charles Vane');
-- INSERT INTO pirates(id, name) VALUES (157, 'Hendrick van Hoven');
-- INSERT INTO pirates(id, name) VALUES (158, 'John Vidal');
-- INSERT INTO pirates(id, name) VALUES (159, 'Thomas Wake');
-- INSERT INTO pirates(id, name) VALUES (160, 'Richard Want');
-- INSERT INTO pirates(id, name) VALUES (161, 'Brigstock Weaver');
-- INSERT INTO pirates(id, name) VALUES (162, 'John West');
-- INSERT INTO pirates(id, name) VALUES (163, 'Joseph Wheeler');
-- INSERT INTO pirates(id, name) VALUES (164, 'Thomas White');
-- INSERT INTO pirates(id, name) VALUES (165, 'David Williams');
-- INSERT INTO pirates(id, name) VALUES (166, 'Paulsgrave Williams');
-- INSERT INTO pirates(id, name) VALUES (167, 'Christopher Winter');
-- INSERT INTO pirates(id, name) VALUES (168, 'Nicholas Woodall');
-- INSERT INTO pirates(id, name) VALUES (169, 'Edward Woodman');
-- INSERT INTO pirates(id, name) VALUES (170, 'Richard Worley');
-- INSERT INTO pirates(id, name) VALUES (171, 'Emanuel Wynn');
-- INSERT INTO pirates(id, name) VALUES (172, 'Charles Yeats');